Repository Cody-Duong/FTC9108-SkyStone, pull requests merged in 2019-12, with the labels that each got.

#66 v1.11.2
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/auto1.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/blueBuildingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/blueLoadingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/redBuildingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/redLoadingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/teleOpMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/test.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Gyro.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Intake.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Lift.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Robot.java
Labels: elevator, enhancement, fix

#67 v1.11.4
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/Auto1.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/BlueBuildingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/BlueLoadingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/RedBuildingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/RedLoadingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/TeleOpMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/Test.java
Labels: fix

#69 v1.12.0
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/Auto1.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/BlueBuildingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/BlueLoadingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/RedBuildingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/RedLoadingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/Test.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/drivers/DirectMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/drivers/TeleOpMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Mecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Robot.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/driver_configuration/Action.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/driver_configuration/ButtonAnalog.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/driver_configuration/ButtonBinary.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/driver_configuration/ButtonSimple.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/driver_configuration/DriverConfiguration.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/robot/BNOIMU.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/robot/ColorSensorGroup.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/robot/DcMotorGroup.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/robot/Intake.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/robot/Lift.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/robot/Mecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/robot/RevHubGroup.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/robot/Robot.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/robot/ServoGroup.java
  build.common.gradle
  build.gradle
Labels: enhancement, fix, mecanum
