Repository Cody-Duong/FTC9108-SkyStone, pull requests merged in 2019-11, with the labels that each got.

#22 9108-V1.1
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto1.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/teleOpMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/general_classes/Pos2D.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/general_classes/Size2D.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/pathfinding/GameObject.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/pathfinding/GameRegion.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/pathfinding/Node.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/pathfinding/Obstacle.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_methods/TeamMethods.java
Labels: enhancement

#24 9108-V1.3
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/auto1.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/teleOpMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/general_classes/Position2DAngle.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_methods/DcMotorGroup.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_methods/TeamMethods.java
Labels: enhancement, fix

#25 Pathfinding
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/general_classes/Position2D.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/general_classes/Size2D.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/pathfinding/Node.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/pathfinding/Obstacle.java
Labels: fix

#37 9108-V1.4
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/teleOpMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_methods/DcMotorGroup.java
Labels: enhancement, fix, mecanum

#38 9108-V1.4R
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_methods/Robot.java
Labels: enhancement

#39 Resolves #34
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/pathfinding/GameRegion.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/pathfinding/Node.java
Labels: fix

#40 9108-V1.6
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/auto1.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/teleOpMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_methods/TeamMethods.java
Labels: enhancement, fix, vision

#41 9108-V1.7
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/auto1.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/teleOpMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_methods/BNOIMU.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_methods/ColorSensorGroup.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_methods/DcMotorGroup.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_methods/Robot.java
Labels: enhancement

#52 9108-V1.7bf
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/teleOpMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/general_classes/Position2DAngle.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/BNOIMU.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/DcMotorGroup.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Robot.java
Labels: fix

#54 Fix
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/teleOpMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/BNOIMU.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Gyro.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Mecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Robot.java
Labels: fix

#55 9108-V1.8
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/auto1.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/teleOpMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/BNOIMU.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/DcMotorGroup.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Gyro.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Mecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Robot.java
Labels: fix

#58 v1.8.1
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/auto1.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/teleOpMecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Mecanum.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Robot.java
Labels: fix

#64 v1.10.3
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/auto1.java
Labels: fix

#65 v1.11.0
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/auto1.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/blueBuildingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/blueLoadingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/redBuildingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/auto_classes/redLoadingZone.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/team_classes/Robot.java
Labels: enhancement, fix
